Revert "[iOS] Remove kReadingListEnableSyncTransportModeUponSignIn in iOS"
This reverts commit c6ced9db12ca52c81c780bc102872108cf2f75f9.

Reason for revert: Compile failure on iOS: https://ci.chromium.org/ui/p/chromium/builders/ci/ios-device/331862/overview

../../ios/chrome/browser/ui/reading_list/reading_list_coordinator.mm:658:13: error: no member named 'kReplaceSyncPromosWithSignInPromos' in namespace 'syncer';

Original change's description:
> [iOS] Remove kReadingListEnableSyncTransportModeUponSignIn in iOS
>
> Remove code related to UNOp1 in iOS.
>
> Change-Id: Iff9a739e915f22f0ae4142e40a7085003d1654c1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5119749
> Commit-Queue: Olivier Robin <olivierrobin@chromium.org>
> Reviewed-by: Olivier Robin <olivierrobin@chromium.org>
> Auto-Submit: Jérôme Lebel <jlebel@chromium.org>
> Code-Coverage: findit-for-me@appspot.gserviceaccount.com <findit-for-me@appspot.gserviceaccount.com>
> Reviewed-by: Mikel Astiz <mastiz@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1239157}

Change-Id: Idc55d82d26e97868d37cb8cb2013a775d7659f6c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5134037
Owners-Override: Matt Jones <mdjones@google.com>
Commit-Queue: Matthew Jones <mdjones@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1239165}
NOKEYCHECK=True
GitOrigin-RevId: bf0a53bc5865f74fb99671279afcaf3e5c892a29