Revert "Reland "[iOS] Add support for notification interaction related NAUs.""
This reverts commit a7041ff7c550577f622b9582a35502f15b39c581.

Reason for revert: This Fix is still braking build with error
error: abstract class is marked 'final'

Original change's description:
> Reland "[iOS] Add support for notification interaction related NAUs."
>
> This reverts commit 6d6beecaeccf7422bb00732c25eb6ff9ca04f3ef.
>
> Reason for revert: Removed call (3 way patch)
>
> Original change's description:
> > Revert "[iOS] Add support for notification interaction related NAUs."
> >
> > This reverts commit bdaf789a1e67d1c7e0c5d8bf9bc11f1723fe0e64.
> >
> > Reason for revert: Breaks compilation - https://ci.chromium.org/ui/p/chrome/builders/ci/simulator-builder/184108/blamelist
> >
> > Original change's description:
> > > [iOS] Add support for notification interaction related NAUs.
> > >
> > > This CL allows feedback related NAUs to be reported when an interaction with a notification is triggered.
> > >
> > > Change-Id: I1d5a53c85417d24ae664a10d2e60c858ba24f572
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5493385
> > > Reviewed-by: Sergio Collazos <sczs@chromium.org>
> > > Commit-Queue: Sergio Collazos <sczs@chromium.org>
> > > Cr-Commit-Position: refs/heads/main@{#1294000}
> >
> > Change-Id: Id217b314f665a923856967d5ed0a0918e2f33211
> > No-Presubmit: true
> > No-Tree-Checks: true
> > No-Try: true
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5500815
> > Auto-Submit: Mike Dougherty <michaeldo@chromium.org>
> > Reviewed-by: Sergio Collazos <sczs@chromium.org>
> > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > Reviewed-by: Guillem Perez <guiperez@google.com>
> > Commit-Queue: Sergio Collazos <sczs@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1294151}
>
> Change-Id: I723dd05621bbf90c2c91b1295582f1f957d191c5
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5499211
> Commit-Queue: Sergio Collazos <sczs@chromium.org>
> Reviewed-by: Sergio Collazos <sczs@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1294166}

Change-Id: Ifdb8541fa219078d2ba090b14bdb0ba5a07ce1bb
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5501137
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Federica Germinario <fedegermi@google.com>
Commit-Queue: Federica Germinario <fedegermi@google.com>
Reviewed-by: Gauthier Ambard <gambard@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1294209}
NOKEYCHECK=True
GitOrigin-RevId: 7cc790f13b34196a7165fc31137a96f874b71d15