[ios] fix remote compiles errors for ios/third_party/earl_grey2
Some objc compiles fail on remote workers for missing header files.

e.g.
```
[120/120] OBJC obj/ios/third_party/earl_grey2/app_framework_shared_library/WKWebView+GREYApp.o
...
fatal error: 'GREYWKWebViewNavigationDelegate.h' file not found
   20 | #import "GREYWKWebViewNavigationDelegate.h"
```

This is because reclient include scanner couldn't find it.
This CL adds the missing include dirs so that the include scanner can
find the header files.

Bug: b/325538963
Change-Id: Ib02f5272b3499b2cf549d2e4f6f69971779593ec
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5300135
Reviewed-by: Justin Cohen <justincohen@chromium.org>
Commit-Queue: Junji Watanabe <jwata@google.com>
Auto-Submit: Junji Watanabe <jwata@google.com>
Commit-Queue: Justin Cohen <justincohen@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1261482}
NOKEYCHECK=True
GitOrigin-RevId: b2aac411127b9f4ee3e5e85c6764ca983bf6e063