Revert "[iOS] Update Share sheet sources"
This reverts commit d78c9d2b2690a8aa0cd8da2b805f692256a3a25e.

Reason for revert: Build is broken with error;
../../ios/chrome/browser/location_bar/ui_bundled/location_bar_view_controller.mm:830:50: error: no known instance method for selector 'showShareSheet'
  830 | [weakSelf.dispatcher showShareSheet];

Original change's description:
> [iOS] Update Share sheet sources
>
> This CL updates the source used to present the share sheet. In
> particular:
> - It replaces the UIBarButtonItem by a sourceItem
> - It replaces the source view by a sourceItem when it uses its bounds as
>   source rect
> - It passes the source view triggering the share menu to correctly
>   anchor the popover on the right button
> - It removes the SharingPositioner protocol as it is no longer needed
>
> https://screenshot.googleplex.com/AJDWFKyCUWrQvdw
>
> Fixed: 479774903
> Change-Id: I170b7ee62ec911d4e08eb7086ea642349a816679
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7532958
> Commit-Queue: Gauthier Ambard <gambard@chromium.org>
> Reviewed-by: Olivier Robin <olivierrobin@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1578159}

Bug: 479774903
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bypass-Check-License: Revert
Change-Id: I98c3778d61442373ddc61de8bf82d0453602257f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7534229
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Samuel Huang <huangs@chromium.org>
Commit-Queue: Federica Germinario <fedegermi@google.com>
Owners-Override: Federica Germinario <fedegermi@google.com>
Reviewed-by: Ginny Huang <ginnyhuang@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1578185}
NOKEYCHECK=True
GitOrigin-RevId: 97b637d6a3086bca6bf03bcb7fb84bb5b991a1aa