Reland "[ios] Disable open incognito tab menu item for Next"
This reverts commit c8c831b2f1cf8de407207abb1296e1d5494d076a.

Reason for revert: race condition Cl landing led to broken tree.
updateConsumerWithWebState: call updated.

Original change's description:
> Revert "[ios] Disable open incognito tab menu item for Next"
>
> This reverts commit bfcd008b639f0eea5fa5b310246869cdddf1bcce.
>
> Reason for revert: Suspected causing tree closure.
>
> Log:
> ../../ios/chrome/browser/toolbar/coordinator/toolbar_mediator.mm:422:13:
> error: no visible @interface for 'ToolbarMediator' declares the selector
> 'updateConsumerWithWebState:'
>   422 |       [self updateConsumerWithWebState:_webStateList->GetActiveWebState()];
>
> Original change's description:
> > [ios] Disable open incognito tab menu item for Next
> >
> > The ButtonFactory was not being refreshed when the user changes sign in
> > state to a supervised profile. This change observes that pref in
> > ToolbarMediator and AppBarMediator.
> >
> > Adds -openToolsMenuOnNTP EG Helper
> > for new entrypoint for tools menu on NTP for Next.
> >
> > Fixed: 514232295
> > Change-Id: I37146730a9845e34de539a7877c41a4a477183a2
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7861464
> > Reviewed-by: Rohit Rao <rohitrao@chromium.org>
> > Commit-Queue: Chris Lu <thegreenfrog@chromium.org>
> > Reviewed-by: Eric Ekey <ericekey@google.com>
> > Cr-Commit-Position: refs/heads/main@{#1634547}
>
> Bug: 514232295
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Change-Id: I3f5288862e12f64da9dd464ace9ad198f5dc6530
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7869876
> Owners-Override: Hailey Wang <haileywang@google.com>
> Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Hailey Wang <haileywang@google.com>
> Cr-Commit-Position: refs/heads/main@{#1634551}

Bug: 514232295
Change-Id: Ib901682e5c946e5ad69e6f6bfe33baba991aa86f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7870223
Auto-Submit: Chris Lu <thegreenfrog@chromium.org>
Reviewed-by: Rohit Rao <rohitrao@chromium.org>
Commit-Queue: Rohit Rao <rohitrao@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1634880}
NOKEYCHECK=True
GitOrigin-RevId: cb19fe13bc9392be8f681fb98d1bca3eebee3fbc